# StatefulSet for Mongodb Server
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dntx-backend-mongodb
  namespace: glenneligio
spec:
  serviceName: "dntx-backend-mongodb-service"
  selector:
    matchLabels:
      app: dntx-backend-mongodb
  template:
    metadata:
      labels:
        app: dntx-backend-mongodb
    spec:
      containers:
        - name: dntx-backend-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "sampleuserprod"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "samplepassprod"
          volumeMounts:
            - mountPath: /data/dntx
              name: dntx-mongodb-data
  volumeClaimTemplates:
    - metadata:
        name: dntx-mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: dntx-backend-mongodb-service
  namespace: glenneligio
spec:
  clusterIP: None
  selector:
    app: dntx-backend-mongodb
  ports:
    - port: 27017
      targetPort: 27017
