# this comes from an okteto secret
name: $DNTX_BACKEND_EMAIL_SENDER_PASSWORD
DNTX_MONGODB_HOST: dntx-backend-mongodb-service
DNTX_MONGODB_PORT: "27017"
DNTX_MONGODB_DATABASE: dntx
DNTX_MONGODB_USERNAME: sampleuserprod
DNTX_MONGODB_PASSWORD: samplepassprod
DNTX_JWT_SECRET_KEY: samplesecretkeyprod
DNTX_BACKEND_EMAIL_SENDER_USERNAME: dntx.supp@gmail.com
