apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dntx-kustomization
  namespace: glenneligio
configMapGenerator:
  - name: dntx-config
    files:
      - config.yml
resources:
  - database.yml
  - frontend.yml
  - backend.yml
