apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dntx-kustomization
  namespace: glenneligio
resources:
  - config.yml
  - database.yml
  - frontend.yml
  - backend.yml
