apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dntx-kustomization
  namespace: glenneligio
configMapGenerator:
  - name: dntx-secrets
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - database.yml
  - frontend.yml
  - backend.yml
  - okteto-ingress.yml
