version: "3.8"

services:
    dntx-backend-spring:
        container_name: dntx-backend-spring
        image: shuntjg/dntx-backend:0.0.2.9-PROD
        restart: always
        networks:
            - dntx-network
        ports:
            - "8090:8080"
        attach: false
        depends_on:
            - dntx-backend-mongodb
        env_file:
            - dntx-config-backend.env
    dntx-backend-mongodb:
        container_name: dntx-backend-mongodb
        image: mongo:7.0.5-rc0
        volumes:
            - type: volume
              source: dntx-data
              target: /data/db
        ports:
            - "27017:27017"
        attach: false
        networks:
            - dntx-network
        env_file:
            - dntx-config-database.env
    dntx-frontend-react:
        container_name: dntx-frontend-react
        image: shuntjg/dntx-frontend:0.0.2.9-PROD
        networks:
            - dntx-network
        attach: false
        depends_on:
            - dntx-backend-spring
        ports: 
            - "80:80"
        env_file:
            - dntx-config-frontend.env
       
volumes:
    dntx-data: 
    
networks:
    dntx-network: