version: 0.0.2.10

services:
    backend:
        image: shuntjg/dntx-backend:0.0.2.9-PROD
        depends_on:
            - database
        restart: always
        environment:
            DNTX_MONGODB_HOST: database
            DNTX_MONGODB_PORT: 27017
            DNTX_MONGODB_DATABASE: dntx
            DNTX_MONGODB_USERNAME: sampleuserprod
            DNTX_MONGODB_PASSWORD: samplepassprod
            DNTX_JWT_SECRET_KEY: samplesecretkeyprod
            DNTX_BE_PORT: 8080
            DNTX_BACKEND_EMAIL_SENDER_PASSWORD: $DNTX_BACKEND_EMAIL_SENDER_PASSWORD
            DNTX_BACKEND_EMAIL_SENDER_USERNAME: dntx.supp@gmail.com
        ports: 
            - "8000:8080"
    frontend:
        image: shuntjg/dntx-frontend:0.0.2.9-PROD
        depends_on:
            - backend
        restart: always
        environment:
            DNTX_BE_SERVICE_NAME: backend
            DNTX_BE_PORT: "8080"
        ports:
            - "80:80"
    database:
        image: mongo:latest
        volumes:
            - database_data:/etc/mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: sampleuserprod
            MONGO_INITDB_ROOT_PASSWORD: samplepassprod
        ports: 
            - "27017:27017"
volumes:
    database_data: 
    