spring:
  data:
    mongodb:
      host: ${DNTX_MONGODB_HOST:localhost}
      port: ${DNTX_MONGODB_PORT:27017}
      database: ${DNTX_MONGODB_DATABASE:dntx}
      auto-index-creation: true
      username: ${DNTX_MONGODB_USERNAME:sampleuser}
      password: ${DNTX_MONGODB_PASSWORD:samplepassword}
      authentication-database: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DNTX_BACKEND_EMAIL_SENDER_USERNAME:dntx.supp@gmail.com} #import the value from env var or java cmd args
    password: ${DNTX_BACKEND_EMAIL_SENDER_PASSWORD:uwzapzmogvgvlqsz} #import the value from env var or java cmd args
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: ${DNTX_BE_PORT:8080}

management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

dntx:
  secret-key: ${DNTX_JWT_SECRET_KEY:sampleKey}